<a href="https://colab.research.google.com/github/MHamza666/numpy/blob/main/data_distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What is Data Distribution?
Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions

A data distribution is a function or a listing which shows all the possible values (or intervals) of the data and how often each value occurs. Data distribution is important when working with statistics and data science. The random module offers method that returns randomly generated data distribution

#Random Distribution:
A random distribution is a set of random numbers that follows a certain probability density function.

#What is Probability Density Function?

A function that describes continuous probability, (i.e.) probability of all values in an array.

We can generate this using the choice() method,.

Probability is set by a number between 0 and 1;

0 : value will never occur.

1 : value will always occur.

As we know, sum of all probability should always be 1.

Example1:

To generate 1–D array that contains 10 values, where each value has to be 1,2,3 or 4.

The probability for the value to be 1 is set to be 0.3

The probability for the value to be 2 is set to be 0.2

The probability for the value to be 3 is set to be 0

The probability for the value to be 4 is set to be 0.5


Running again;


How many ever times you try to run the program, value 3 will never occur. This is because we have assigned/set the probability of 3 to be ‘0’.

You can also return arrays of any shape and size by specifying the shape in the size parameter.

Example2:

To generate 2-D array with 3 rows, each row containing 4 values;


Random Permutation:
Permutation refers to changing the arrangement of elements.

Numpy random module provides two methods for this:

· shuffle()

· permutation()

shuffle():

It changes the arrangement of elements in-place (in the array itself).

(i.e.) changes are made to the original array.


permutation():

It changes the arrangement of elements as copy.

(i.e.) changes are made by returning the re-arranged array without changing the original array.



Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0

# choice method()

In [13]:
from numpy import random
varr = random.choice([3,5,7,9], p=[0.1 , 0.3 , 0.6 ,0.0], size = (100)) # p mean probability
print(varr)

[7 7 7 7 5 5 5 7 7 7 7 3 7 7 3 5 7 7 5 7 5 5 3 7 7 5 3 7 5 5 7 7 7 5 7 3 7
 7 7 3 3 7 7 7 7 7 5 5 7 5 7 3 5 3 7 7 7 7 3 5 7 7 7 7 7 5 3 7 7 7 5 7 7 3
 7 7 7 5 7 7 7 7 5 5 3 5 5 5 7 5 7 7 3 5 7 7 7 7 7 7]


In [14]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[5 5 7 7 5]
 [7 7 7 7 5]
 [7 5 7 7 3]]


#Random Permutations of Elements
A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: shuffle() and permutation()

#Shuffling Arrays
Shuffle means changing arrangement of elements in-place. i.e. in the array itself

In [16]:
from numpy import random
import numpy as np
arr = np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)

[5 4 1 2 3]


# Generating Permutation of Arrays

In [19]:
from numpy import random
import numpy as np
arr1 = np.array([6,5,4,3,2,1])

print(random.permutation(arr1))

[5 1 3 2 6 4]
