<a href="https://colab.research.google.com/github/MHamza666/numpy/blob/main/linspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[[12,13,14,15,16],[13,65,87,33,45]],[[32,24,24,5,4],[12,54,65,22,12]]]])
print(A)
print("Slicing ")
print(A[0:4:2 ,1:3:2])

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]

  [[12 13 14 15 16]
   [13 65 87 33 45]]

  [[32 24 24  5  4]
   [12 54 65 22 12]]]]
Slicing 
[[[[12 13 14 15 16]
   [13 65 87 33 45]]]]


In [7]:
import numpy as np
arr = np.linspace(0,5)
print(arr)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [8]:
import numpy as np
arr = np.linspace(0,4,6)
print(arr)

[0.  0.8 1.6 2.4 3.2 4. ]


In [9]:
import numpy as np
arr = np.linspace(0,5,10)
print(arr)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [10]:
import numpy as np
arr = np.linspace(2.0,5.0)
print(arr)

[2.         2.06122449 2.12244898 2.18367347 2.24489796 2.30612245
 2.36734694 2.42857143 2.48979592 2.55102041 2.6122449  2.67346939
 2.73469388 2.79591837 2.85714286 2.91836735 2.97959184 3.04081633
 3.10204082 3.16326531 3.2244898  3.28571429 3.34693878 3.40816327
 3.46938776 3.53061224 3.59183673 3.65306122 3.71428571 3.7755102
 3.83673469 3.89795918 3.95918367 4.02040816 4.08163265 4.14285714
 4.20408163 4.26530612 4.32653061 4.3877551  4.44897959 4.51020408
 4.57142857 4.63265306 4.69387755 4.75510204 4.81632653 4.87755102
 4.93877551 5.        ]


In [11]:
import numpy as np
arr = np.linspace(3,6,8)
print(arr)

[3.         3.42857143 3.85714286 4.28571429 4.71428571 5.14285714
 5.57142857 6.        ]
