<a href="https://colab.research.google.com/github/MHamza666/numpy/blob/main/random_lecture_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# randint()
the function is used to generate a random number


In [1]:
# varr5 = np.random.randint(min,max,totall_number)
import numpy as np
varr5 = np.random.randint(5,30,8)
print(varr5)

[ 6 13  5 18 23 18 23  7]


In [3]:
# 2nd example
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
import numpy as np
varr = np.random.randint(100,size=(2,5))
print(varr)

[[70  5 44 25  7]
 [93 58 25 46  2]]


In [6]:
from numpy import random
varr2 = random.randint(200,size=5)
print(varr2)

[139  37 146  41  92]


# choice method ()

The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array

In [10]:
from numpy import random
x = random.choice([1,2,3,4,5],size = 3)
print(x)

[3 5 3]


In [9]:
import numpy as np
a = np.random.choice([1,2,3,4,5,6],size=(2,5))
print(a)

[[1 4 3 4 6]
 [3 6 1 2 3]]
