<a href="https://colab.research.google.com/github/MHamza666/numpy/blob/main/random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# rand()

In [7]:
import numpy as np
var1 = np.random.rand(5)
print(var1)

[0.31745521 0.64645347 0.1002871  0.80537834 0.76845873]


In [8]:
var2 = np.random.rand(2,5)
print(var2)

[[0.46504812 0.88154865 0.26184145 0.65309897 0.73325018]
 [0.27916463 0.40841576 0.75258834 0.95577412 0.64436876]]


# randn()

In [10]:
# this function is used to generate random value and this value is close to zero
# and the may return positive number and negative number as well

import numpy as np
varr3 = np.random.randn(5)
print(varr3)

[ 0.03696602  0.7736846  -1.12809742  1.73937191  0.44267395]


# ranf()
the function for doing random sampling in numpy it returns an array of specified  shape and fills it with random floats in the half ioen interval

In [12]:
import numpy as np
varr4 = np.random.ranf(5)
print(varr4)

[0.47399376 0.30721797 0.11270067 0.30285982 0.99394632]


# randint()
the function is used to generate a random number


In [13]:
# varr5 = np.random.randint(min,max,totall_number)
import numpy as np
varr5 = np.random.randint(5,30,8)
print(varr5)

[29 28 28 14 29 23  7  8]
