<a href="https://colab.research.google.com/github/MHamza666/numpy/blob/main/repeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy.repeat()
This function repeats the elements of the array passed as its argument and returns a newly generated array.



numpy.repeat(arr, repetitions, axis = None)


→ Arr - refers to the input array.



→ Repetitions - refers to the no. of repetitions of each array element.



→ Axis - refers to the axis along which we wish to return values.

In [23]:
import numpy as np
arr1 = [1,2,3,4,5]



list1= np.repeat(arr1, 2, axis=0)

print(list1)

[1 1 2 2 3 3 4 4 5 5]


In [29]:
import numpy as np
arr = [6,7,8,9,0]
list=np.repeat(arr,2,axis=0)
print(list)

[6 6 7 7 8 8 9 9 0 0]


In [30]:
import numpy as np
arr = np.array([1,2,3,4,5])
list=np.repeat(arr,3)
print(list)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [34]:
import numpy as np
arr = np.array([[1,2,3,4],[6,7,8,9]])
list =np.repeat(arr,3,axis=0)
print(list)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [6 7 8 9]
 [6 7 8 9]
 [6 7 8 9]]


In [35]:
import numpy as np
arr = np.array([[1,2,3,4],[6,7,8,9]])
list =np.repeat(arr,3,axis=1)
print(list)

[[1 1 1 2 2 2 3 3 3 4 4 4]
 [6 6 6 7 7 7 8 8 8 9 9 9]]
