In [1]:
import numpy as np
a = np.zeros(3)
print(a)

[0. 0. 0.]


In [3]:
import numpy as np
a = np.zeros((3 ,6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
import numpy as np
a = np.zeros((3 ,6 ,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [5]:
import numpy as np
a = np.ones((3 ,6 ,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [14]:
import numpy as np
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [18]:
import numpy as np
a = np.linspace(0,5,10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [25]:
import numpy as np
b = np.arange(1,10 ,2)
print("orignal array",b)
a = b.reshape(5,1)
print("reshape",a)

orignal array [1 3 5 7 9]
reshape [[1]
 [3]
 [5]
 [7]
 [9]]


In [28]:
import numpy as np
b = np.arange(1,20 ,2)
print("orignal array",b)
a = b.reshape(5,2)
print("reshape",a)

orignal array [ 1  3  5  7  9 11 13 15 17 19]
reshape [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [29]:
import numpy as np
b = np.random.rand(1,20)
print("orignal array",b)

orignal array [[0.40022773 0.27327404 0.67032033 0.94387812 0.94914613 0.37578713
  0.80275935 0.69053664 0.50988843 0.05109027 0.81681552 0.67804838
  0.87961423 0.88377006 0.29837826 0.46073081 0.07082566 0.33836241
  0.37241757 0.33804662]]


# Topic 03= Array indexing()

In [30]:
import numpy as np 
a = np.array([21,4,35,6,57,87,86989,4,845,34,786,24,75,12,7])
print(a)

[   21     4    35     6    57    87 86989     4   845    34   786    24
    75    12     7]


In [32]:
import numpy as np 
a = np.array([21,4,35,6,57,87,86989,4,845,34,786,24,75,12,7])
print(a[6])

86989


In [34]:
import numpy as np 
a = np.array([21,4,35,6,57,87,86989,4,845,34,786,24,75,12,7])
print(a[-5])

786


In [ ]:
A = np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[12,13,14,15,16],[[13,65,87,33,45][]],[]]) 