# 1 dimensional or 1D array

In [16]:
import numpy as np
a =np.array(['a','b','c','d'])
print(a)

['a' 'b' 'c' 'd']


In [3]:
import numpy as np
a =np.array([1,2,3,4,5,67,])
print(a)

[ 1  2  3  4  5 67]


In [4]:
import numpy as np
a =np.array(['1','2','3','4'])
print(a)

['1' '2' '3' '4']


In [5]:
import numpy as np
a =np.array(['1','2','3','4'])
print("Orignal Array" ,a)
b =np.ndim(a)# this code use for to check deminsional of array
print("Demnsional of array:",b)

Orignal Array ['1' '2' '3' '4']
Demnsional of array: 1


In [6]:
import numpy as np
a =np.array(['1','2','3','4'])
print("Orignal Array" ,a)
b =np.ndim(a)# this code use for to check deminsional of array
print("Demnsional of array:",b)
c = np.shape(a)
print(c)

Orignal Array ['1' '2' '3' '4']
Demnsional of array: 1
(4,)


In [7]:
import numpy as np
a =np.array(['1','2','3','4'])
print("Orignal Array" ,a)
b =np.ndim(a)# this code use for to check deminsional of array
print("Demnsional of array:",b)
c = np.shape(a)
print(c)
n = np.size(a)
print(n)

Orignal Array ['1' '2' '3' '4']
Demnsional of array: 1
(4,)
4


# 2 Deminsioinal array OR 2D Array 

In [8]:
import numpy as np
a = np.array([[1,2,3,4,5]])
print(a)
b = np.ndim(a)
print("No Of Deminsional:",b)

[[1 2 3 4 5]]
No Of Deminsional: 2


In [9]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a)
b = np.ndim(a)
print("No Of Deminsional:",b)

[[1 2 3 4 5]
 [6 7 8 9 0]]
No Of Deminsional: 2


In [10]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a)
b = np.ndim(a)
print("No Of Deminsional:",b)
s = np.shape(a)
print("shape:",s)

[[1 2 3 4 5]
 [6 7 8 9 0]]
No Of Deminsional: 2
shape: (2, 5)


# 3 Deminsioinal array OR 3D Array

In [11]:
import numpy as np
a = np.array([[[1,2,3,4,5],[6,7,8,9,0]]])
print(a)
b = np.ndim(a)
print("No Of Deminsional:",b)
s = np.shape(a)
print("shape:",s)

[[[1 2 3 4 5]
  [6 7 8 9 0]]]
No Of Deminsional: 3
shape: (1, 2, 5)


In [12]:
import numpy as np
a = np.array([[[[1,2,3,4,5],[6,7,8,9,0]]]])
print(a)
b = np.ndim(a)
print("No Of Deminsional:",b)
e = np.size(a)
print("Size of the array", e)
s = np.shape(a)
print("shape:",s)

[[[[1 2 3 4 5]
   [6 7 8 9 0]]]]
No Of Deminsional: 4
Size of the array 10
shape: (1, 1, 2, 5)


In [13]:
import numpy as np
a = np.array([[[[1,2,3,4,5],[6,7,8,9,0]], [[24,23,24,53,67],[31,11,43,56,6]]]])
print(a)
b = np.ndim(a)
print("No Of Deminsional:",b)
e = np.size(a)
print("Size of the array", e)
s = np.shape(a)
print("shape:",s)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9  0]]

  [[24 23 24 53 67]
   [31 11 43 56  6]]]]
No Of Deminsional: 4
Size of the array 20
shape: (1, 2, 2, 5)


In [14]:
a = np.array([1,23,4,5], dtype=float)
print(a)

[ 1. 23.  4.  5.]


In [15]:
a = np.array([1,23,4,5], dtype=str)
print(a)

['1' '23' '4' '5']


In [17]:
a = np.array([1,23,4,5], dtype=complex)
print(a)

[ 1.+0.j 23.+0.j  4.+0.j  5.+0.j]


In [18]:
a = np.array([1,23,4,5], ndmin=10)
print(a)

[[[[[[[[[[ 1 23  4  5]]]]]]]]]]


In [19]:
a = np.array([1,23,4,5], ndmin=10)
print(a.dtype)


int32


In [21]:
import numpy as np
a = np.array(['d','rew','sds'], ndmin=10)
print(a.dtype)

<U3
