In [3]:
import numpy as np
a = [1,2,3,4,5,6]
b = [7,8,9,10,11,6]
c = [12,13,14,15,16,17]
d = [18,19,20,21,22,23]
s =np.array([a,b,c])
print(s)
print(np.size(s))
print(s[1:3,1:6:2])


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  6]
 [12 13 14 15 16 17]]
18
[[ 8 10  6]
 [13 15 17]]
